  server:
    port: 8180

  spring:
    application:
      name: troubleshoot
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.85.100:3306/pg_ts?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: sysadmin
      password: adminsys
    #    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/pg_ts?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    #    username: root
    #    password:
    redis:
      database: 0
      host: 192.168.85.100
      port: 6379
      password: 111111
      timeout: 3000
      jedis:
        pool:
          max-active: 8 #最大连接数
          max-wait: 2000   #最大阻塞等待时间(负数表示没限制)
          max-idle: 8  #最大空闲
          min-idle: 0  #最小空闲

    #---------------mybatis-plus配置-------------------
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: com.yl.data.entity
    # 以下配置均有默认值,可以不设置
    global-config:
      db-config:
          #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
        field-strategy: NOT_EMPTY
           #数据库类型
         db-type: mysql
      configuration:
        # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
         map-underscore-to-camel-case: true
        # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
          call-setters-on-nulls: true
        # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
           log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    root: INFO
    org.springframework: INFO
    org.mybatis: DEBUG
    com.econ.powercloud: DEBUG

    emos:
    2. jwt:
    3. #密钥
    4. secret: abc123456
    5. #令牌过期时间（天）
    6. expire: 5
    7. #令牌缓存时间（天数）
    8. cache-expire: 10
